#!/usr/bin/python

# USAGE:
#
# Once running, press the following keys:
#
# 's' will note that a rep has started
# 'g' will note that a rep has ended, and is valid
# 'h' will note that a rep has ended, and is invalid
# 'x' will stop the program

good_reps = 0
bad_reps = 0

import serial, time, sys, curses

# Setup curses to catch keystrokes
window = curses.initscr()
window.nodelay(1)
window.keypad(1)

def main(window):

    # Check argument(s). 
    #
    # First arg is filename. 
    # This should be the path from project/ to the file
    #
    # E.G. 'data/daniel/set1'
    #
    # This will create the file project/data/daniel/set1.txt
    # Note that the directory must already exist
    #
    # Existing files should be appended to instead of overwritten


    if len(sys.argv) < 2:
        print "No filename given; try again."
        sys.exit(1)
    else:
        filename = sys.argv[1] + ".txt"

    # Create new text file
    logfile = open(filename,"a+")

    # Open a Serial connection to the Arduino:
    print "Connecting..."
    try:
        arduino = serial.Serial('/dev/ttyACM0', 9600, timeout=1)
    except:
        print "Failed to connect on /dev/ttyACM0"
        sys.exit(2)

    print "success"

    # Read input from Serial and write to to the file, as well as to the screen
    # Will exit when any character is pressed
    ch = -1

    global good_reps
    global bad_reps

    while ch != ord('x'):
        line = arduino.readline()
        print line
        logfile.write(line)
        ch = window.getch()
        if ch == ord('s'):
            logfile.write("Repetition Start\n")
            print "Repetition Start\n"
        if ch == ord('g'):
            logfile.write("Repetition End\n")
            logfile.write("1\n")
            good_reps += 1
            print "Repetition End (good rep)\n"
        if ch == ord('h'):
            logfile.write("Repetition End\n")
            logfile.write("0\n")
            bad_reps += 1
            print "Repetition End (bad rep)\n"

    logfile.close()

curses.wrapper(main)

print "Finished logging. Recorded {} reps: {} good form and {} bad form".format(good_reps + bad_reps, good_reps, bad_reps)

sys.exit(0)